services:
  ego-bot:
    container_name: ego-bot
    image: jasontulp/movie-bot:latest
    # volumes:
    #   - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped
    networks:
      - t2_proxy
      - socket_proxy
    ports:
      - "3031:3031"
    build: .
    environment:
      TZ: $TZ
      PUID: $PUID
      PGID: $PGID
      VITE_RADARR_API_KEY: 'e985a534af0947c2b46953e972844f0c'
      VITE_PORT: 3031
      VITE_RADARR_API_URL: 'https://radarr.tulp.dev/api/v3'
      VITE_OLLAMA_API_URL: 'https://ollama.tulp.dev'
      VITE_DOMAIN: 'ego.tulp.dev'
      VITE_OLLAMA_MODEL_NAME: 'ego-bot'
    labels:
      - "traefik.enable=true"
      # HTTP Routers
      - "traefik.http.routers.ego-bot-rtr.entrypoints=websecure"
      - "traefik.http.routers.ego-bot-rtr.rule=Host(`ego.$DOMAINNAME`)"
      # Middlewares
      - "traefik.http.routers.ego-bot-rtr.middlewares=chain-no-auth@file"
      # HTTP Services
      - "traefik.http.routers.ego-bot-rtr.service=ego-bot-svc"
      - "traefik.http.services.ego-bot-svc.loadbalancer.server.port=3031"