# Jackett - Torrent proxy
# Set url_base in Jackett settings if using PathPrefix
services:
  jackett:
    image: lscr.io/linuxserver/jackett:latest
    container_name: jackett
    restart: unless-stopped
    networks:
      t2_proxy:
        ipv4_address: 192.168.90.100
      socket_proxy:
    # ports:
    #  - "9117:9117"
    volumes:
      - $DOCKERDIR/appdata/jackett:/config
      - /home/jason/downloads:/downloads
      - "/etc/localtime:/etc/localtime:ro"
    environment:
      - TZ=$TZ
      - PUID=$PUID
      - PGID=$PGID
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.jackett-rtr.entrypoints=websecure"
      - "traefik.http.routers.jackett-rtr.rule=Host(`jackett.$DOMAINNAME`)"
      ## Middlewares
      - "traefik.http.routers.jackett-rtr.middlewares=chain-no-auth@file"
      ## HTTP Services
      - "traefik.http.routers.jackett-rtr.service=jackett-svc"
      - "traefik.http.services.jackett-svc.loadbalancer.server.port=9117"
