services:
  jellyfin:
    container_name: jellyfin
    image: jellyfin/jellyfin:10.10.3
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    networks:
      - t2_proxy
      - socket_proxy
    runtime: nvidia  # Use NVIDIA runtime
    ports:
      - "8096:8096"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    volumes:
      - $DOCKERDIR/appdata/jellyfin/config:/config
      - $DOCKERDIR/appdata/jellyfin/cache:/cache
      - type: bind
        source: /media/movies
        target: /movies
      - type: bind
        source: /media/tv
        target: /tv
      - type: bind
        source: /media2/movies
        target: /movies2
      - type: bind
        source: /media2/tv
        target: /tv2
    environment:
      TZ: $TZ
      PUID: $PUID
      PGID: $PGID
      gpus: all
      NVIDIA_VISIBLE_DEVICES: all
      NVIDIA_DRIVER_CAPABILITIES: all  # Ensure the container has full access
    labels:
      - "traefik.enable=true"
      # HTTP Routers
      - "traefik.http.routers.jellyfin-rtr.entrypoints=websecure"
      - "traefik.http.routers.jellyfin-rtr.rule=Host(`jellyfin.$DOMAINNAME`) || Host(`stream.$DOMAINNAME`)"
      # Middlewares
      - "traefik.http.routers.jellyfin-rtr.middlewares=chain-no-auth@file"
      # HTTP Services
      - "traefik.http.routers.jellyfin-rtr.service=jellyfin-svc"
      - "traefik.http.services.jellyfin-svc.loadbalancer.server.port=8096"
