services:
  movie-bot:
    container_name: movie-bot
    image: jasontulp/movie-bot:latest
    # volumes:
    #   - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped
    networks:
      - t2_proxy
      - socket_proxy
    ports:
      - "3030:3030"
    build: .
    environment:
      TZ: $TZ
      PUID: $PUID
      PGID: $PGID
      VITE_RADARR_API_KEY: 'e985a534af0947c2b46953e972844f0c'
      VITE_PORT: 3030
      VITE_RADARR_API_URL: 'https://radarr.tulp.dev/api/v3'
      VITE_OLLAMA_API_URL: 'https://ollama.tulp.dev'
      VITE_DOMAIN: 'chat.tulp.dev'
      VITE_OLLAMA_MODEL_NAME: 'jason-bot-2'
    labels:
      - "traefik.enable=true"
      # HTTP Routers
      - "traefik.http.routers.movie-bot-rtr.entrypoints=websecure"
      - "traefik.http.routers.movie-bot-rtr.rule=Host(`chat.$DOMAINNAME`)"
      # Middlewares
      - "traefik.http.routers.movie-bot-rtr.middlewares=chain-no-auth@file"
      # HTTP Services
      - "traefik.http.routers.movie-bot-rtr.service=movie-bot-svc"
      - "traefik.http.services.movie-bot-svc.loadbalancer.server.port=3030"