services:
  # phpMyAdmin - Database management
  # Create a new user with admin privileges. Cannot login as MySQL root for some reason.
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    #profiles: ["apps", "all"]
    networks:
      - t2_proxy
      - socket_proxy
    environment:
      - PMA_HOST=$MARIADB_HOST
      - PMA_PORT=3306
      - PMA_ARBITRARY=1
      - FILE__MYSQL_ROOT_PASSWORD=/run/secrets/mysql_root_password # Note FILE__ (double underscore) - Issue #127
    secrets:
      - mysql_root_password
    labels:
      - "traefik.enable=true"
      # HTTP Routers
      - "traefik.http.routers.phpmyadmin-rtr.entrypoints=websecure"
      - "traefik.http.routers.phpmyadmin-rtr.rule=Host(`pma.$DOMAINNAME`)"
      # Middlewares
      - "traefik.http.routers.phpmyadmin-rtr.middlewares=chain-basic-auth@file"
      # HTTP Services
      - "traefik.http.routers.phpmyadmin-rtr.service=phpmyadmin-svc"
      - "traefik.http.services.phpmyadmin-svc.loadbalancer.server.port=80"
