services:
  quilt-planner:
    container_name: quilt-planner
    image: jasontulp/quilt-planner:latest
    # volumes:
    #   - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped
    networks:
      - t2_proxy
      - socket_proxy
    ports:
      - "5000:5000"
    build: .
    environment:
      TZ: $TZ
      PUID: $PUID
      PGID: $PGID
    labels:
      - "traefik.enable=true"
      # HTTP Routers
      - "traefik.http.routers.quilt-planner-rtr.entrypoints=websecure"
      - "traefik.http.routers.quilt-planner-rtr.rule=Host(`quilt.$DOMAINNAME`)"
      # Middlewares
      - "traefik.http.routers.quilt-planner-rtr.middlewares=chain-no-auth@file"
      # HTTP Services
      - "traefik.http.routers.quilt-planner-rtr.service=quilt-planner-svc"
      - "traefik.http.services.quilt-planner-svc.loadbalancer.server.port=5000"