services:
  valheim:
    image: ghcr.io/lloesche/valheim-server
    container_name: valheim
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    # networks:
    #   - t2_proxy
    #   - socket_proxy
    cap_add:
      - sys_nice
    volumes:
      - $DOCKERDIR/appdata/valheim/config:/config
      - $DOCKERDIR/appdata/valheim/data:/opt/valheim
    ports:
      - 2456-2457:2456-2457/udp
      - 9001:9001
    environment:
      - SERVER_NAME="Tulpheim"
      - WORLD_NAME="Heimlich"
      - SERVER_PASS=penis
      - SERVER_PUBLIC=true
      - STATUS_HTTP=true
      - SUPERVISOR_HTTP=true
      - SUPERVISOR_HTTP_PORT=9001
      - SUPERVISOR_HTTP_USER=admin
      - SUPERVISOR_HTTP_PASS=penis
      - TZ=CEST
      - BACKUPS_MAX_COUNT=5
      - VALHEIM_PLUS=false
      - BEPINEX=false
    # stop_grace_period: 2m
    # labels:
    #   - "traefik.enable=true"
    #   # HTTP Routers
    #   - "traefik.http.routers.valheim-rtr.entrypoints=websecure"
    #   - "traefik.http.routers.valheim-rtr.rule=Host(`valheim-dash.$DOMAINNAME`)"
    #   - "traefik.http.routers.valheim.tls=true"
    #   - "traefik.http.routers.valheim.tls.certresolver=production"
    #   # Middlewares
    #   - "traefik.http.routers.valheim-rtr.middlewares=chain-no-auth@file"
    #   # HTTP Services
    #   - "traefik.http.routers.valheim-rtr.service=valheim-svc"
    #   - "traefik.http.services.valheim-svc.loadbalancer.server.port=9001"
    #   # UDP Services
    #   - "traefik.udp.routers.valheim.rule=Host(`valheim.$DOMAINNAME`)"
    #   - "traefik.udp.routers.valheim.entrypoints=valheimSix,valheimSeven"
    #   - "traefik.udp.services.valheim.loadbalancer.server.port=2456,2457"